-- サンプル
CREATE TABLE lf_sample
(
id SERIAL NOT NULL,
title VARCHAR(20) NOT NULL,
content VARCHAR(255) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);

-- ログインユーザ
CREATE TABLE lf_user
(
user_id VARCHAR(20) NOT NULL
,login_password VARCHAR(30) NOT NULL
,nickname VARCHAR(20) NOT NULL
,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
,PRIMARY KEY (user_id)
);

-- 記事
CREATE TABLE lf_article
(
article_id SERIAL NOT NULL
,user_id VARCHAR(20) NOT NULL
,title VARCHAR(30) NOT NULL
,content VARCHAR
,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
,PRIMARY KEY (article_id)
);

-- 返答
CREATE TABLE lf_reply
(
reply_id SERIAL NOT NULL
,article_id SERIAL NOT NULL
,user_id VARCHAR(20) NOT NULL
,comment VARCHAR(500) NOT NULL
,delete_flag INTEGER NOT NULL DEFAULT 0
,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
,PRIMARY KEY (reply_id)
);
